version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./dockerfiles/static:/static
      - ./dockerfiles/media:/media
    depends_on:
      - web
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./dockerfiles/db_data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    env_file:
      - ${ENV_FILE}.env
    command: ./docker-entrypoint.sh db
    volumes:
      - ./src:/src
      - ./dockerfiles/static:/static
      - ./dockerfiles/media:/media
    expose:
      - "8000"
    depends_on:
      - db
