version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./dockerfiles/config/nginx:/etc/nginx/conf.d
      - ./dockerfiles/media:/media:ro
      - static_volume:/static:ro
    depends_on:
      - web
  db:
    restart: always
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./dockerfiles/db_data:/var/lib/postgresql/data
  web:
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    env_file:
      - ./dockerfiles/.envs/.env
    command: /docker-entrypoint.sh db
    volumes:
      - ./src:/src
      - ./dockerfiles/media:/media
      - static_volume:/static
    expose:
      - "8000"
    depends_on:
      - db

volumes:
  static_volume: